###########################################################
### 欢迎使用 Beautiful Jekyll！
### 此配置文件用于设置整个网站的通用选项。初次搭建网站时，
### 请仔细阅读并编辑以下所有选项，之后通常无需再次修改。
###########################################################

############################
# --- 必须配置的选项 --- #
############################

# 网站名称（显示在标题和导航栏）
title: Majesticrise'blog

# 您的姓名（显示在页脚）
author: Majesticrise

###############################################
# --- 导航栏链接列表 --- #
###############################################

navbar-links:
  About Me: "aboutme"
  Resources:
    - Minebbs插件: "https://www.minebbs.com/members/majesticrise.122701/“
  Author's home: "https://space.bilibili.com/3493114226411557"

################
# --- 网站标志 (Logo) --- #
################

# 导航栏中显示的图片，建议使用正方形图片
# 如果不想在导航栏显示图片，请删除此参数
avatar: "/assets/img/avatar-icon.png"

# 默认会将图片裁剪为圆形，若想禁用此行为，请将下面的值设为 false
round-avatar: true

# 如果想在左上角使用图片 Logo 代替网站标题，请指定以下参数
#title-img: /path/to/image


#####################################
# --- 页脚社交网络链接 --- #
#####################################

# 选择要在页脚显示的社交网络链接。
# 您可以调整顺序以改变显示顺序。
# 取消注释您想显示的链接，并填入您的信息。
social-network-links:
  email: "majesticrise@qq.com"
  github: https://github.com/Majesticrise
#  medium: yourname
#  reddit: yourname or r/yoursubreddit
#  linkedin: daattali
#  xing: yourname
#  stackoverflow: "3943160/daattali"
#  snapchat: deanat78
#  instagram: deanat78
#  spotify: yourname
#  telephone: +14159998888
#  steam: deanat78
#  twitch: yourname
#  yelp: yourname
#  telegram: yourname
#  calendly: yourname
#  mastodon: instance.url/@username
#  bluesky: yourname
#  ORCID: your ORCID ID
#  google-scholar: your google scholar
#  discord: "invite_code" or "users/userid" or "invite/invite_code"
#  kaggle: yourname
#  hackerrank: yourname
#  gitlab: yourname
#  itchio: yourname
#  untappd: yourname
#  strava: youruserid

# 如果希望网站生成 RSS 订阅源，请提供一段描述
# 订阅源的 URL 为 https://<您的网站>/feed.xml
rss-description: This website is a virtual proof that I'm awesome

###########################
# --- 通用选项 --- #
###########################

# 选择在文章中显示哪些社交网络分享按钮
share-links-active:
  twitter: false
  facebook: false
  linkedin: false
  vk: false
  reddit: false

# 页脚中显示网站链接的方式（去掉则不在页脚显示链接）
url-pretty: "majesticrise.github.io/"

# 是否在每个页面的标题中都加上网站标题
title-on-all-pages: true

# 摘要长度 - 在 feed 页面上将每篇文章的摘要截断为指定字数
excerpt_length: 50

# 是否在 feed 页面的每篇博客预览下方显示摘要
feed_show_excerpt: true

# 是否在 feed 页面的每篇博客预览下方显示标签列表
feed_show_tags: true

# 在导航栏中添加搜索按钮
post_search: true

# 在页脚添加“编辑当前页面”按钮（仅当网站托管在 GitHub 上时有效）
edit_page_button: true

# 允许子菜单项（二级导航菜单）比一级菜单更长
# 如果关闭此设置，较长的子菜单单词可能会被截断
# 有关此设置解决的问题，请参见 https://github.com/daattali/beautiful-jekyll/issues/765
navbar-var-length: false

# 用于 SEO 的网站关键词
#keywords: "my,list,of,keywords"

######################################
# --- 颜色 / 背景图片 --- #
######################################

# 自定义网站颜色。颜色值可以是任何有效的 CSS 颜色值。

page-col: "#FFFFFF"
text-col: "#404040"
link-col: "#008AFF"
hover-col: "#0085A1"
navbar-col: "#EAEAEA"
navbar-text-col: "#404040"
navbar-border-col: "#DDDDDD"
footer-col: "#EAEAEA"
footer-text-col: "#777777"
footer-link-col: "#404040"
footer-hover-col: "#0085A1"

# 也可以使用图片替代颜色作为导航栏、页脚和页面背景
#navbar-img: "/assets/img/bgimage.png"
#footer-img: "/assets/img/bgimage.png"
#page-img: "/assets/img/bgimage.png"

# 为移动浏览器建议一种颜色作为浏览器主题色（仅少数移动浏览器支持）
#mobile-theme-col: "#0085A1"

# 如需额外的视觉定制，可以在每个页面中添加额外的 CSS 文件。在此列出您的自定义 CSS 文件
#site-css:
#  - "/assets/css/custom-styles.css"

# 如果有通用的 JavaScript 文件需要在每个页面中引入，请在此列出
#site-js:
#  - "/assets/js/custom-script.js"

#################################
# --- 网站分析统计 --- #
#################################

# 填入您的 Google Analytics 跟踪 ID（或“Measurement ID”）以跟踪网站使用情况
#gtag: "G-XXXXXXXXXX"

# 填入您的 Cloudflare Analytics 令牌以使用 Cloudflare 分析
#cloudflare_analytics: ""

# Google Tag Manager ID
#gtm: ""

# Matomo（即 Piwik）网站统计
# 取消注释以下部分以启用 Matomo。opt-out 参数控制是否允许用户选择退出跟踪。
#matomo:
#  site_id: "9"
#  uri: "demo.wiki.pro"
#  opt-out: true

# Google Universal Analytics ID -- 已弃用
# 自 2023 年 7 月起，Google 不再支持此方式！如果您仍在使用 `google_analytics`，
# 应改用上面的 `gtag` 字段。
#google_analytics: "UA-XXXXXXXX-X"

####################
# --- 评论系统 --- #
####################

# 使用 Disqus 评论，请前往 https://disqus.com 注册并填写您的 Disqus shortname（不是用户 ID）
#disqus: ""

# 使用 Facebook 评论，请创建 Facebook 应用并填写 Facebook App ID
#fb_comment_id: ""

# 使用 CommentBox，请在 https://commentbox.io 注册项目 ID
#commentbox: "" # 项目 ID，例如 "5694267682979840-proj"

# 使用 Utterances 评论：（0）取消注释以下部分，（1）填写 "repository"（确保仓库公开），
# （2）在您的仓库中启用 Issues，（3）在仓库中安装 Utterances 应用 https://github.com/apps/utterances
# 有关以下参数的更多详情，请访问 https://utteranc.es/
#utterances:
#  repository: # GitHub 用户名/仓库名，例如 "daattali/beautiful-jekyll"
#  issue-term: title   # 博客文章与 GitHub Issue 的映射方式
#  theme: github-light # Utterances 主题
#  label: blog-comments # 由 Utterances 创建的 GitHub Issue 所分配的标签

# 使用 Staticman 评论，请取消注释以下部分。如果您不使用 reCaptcha 进行垃圾防护，可保留注释。
# 使用 Staticman 需要较高的技术知识，请参考
# https://github.com/eduardoboucas/staticman/ 和 https://staticman.net/ 进一步了解。
# 任何关于 staticman 的支持问题，请直接咨询 staticman 团队，而非 BeautifulJekyll。
#staticman:
#  repository : # GitHub 用户名/仓库名，例如 "daattali/beautiful-jekyll"
#  branch     : master # 如果您不使用 `master` 分支，则还需更新 `staticman.yml` 中的 `branch` 参数
#  endpoint   : # 您的部署 API 地址，末尾带斜杠，例如 "https://<your-api>/v3/entry/github/"
#  reCaptcha:   # （可选）以下参数也需在 `staticman.yml` 中设置
#    siteKey  : # 您需要在 Google 申请 site key
#    secret   : # 通过访问 https://<your-own-api>/v3/encrypt/<your-site-secret> 加密您的密码

# 使用 giscus 评论：
# （0）取消注释以下 giscus 部分，（1）在您的 GitHub 仓库中启用 Discussions，
# （2）在仓库中安装 giscus 应用（详情见 https://giscus.app），
# （3）填写下面 *全部* 参数
# 有关 giscus 及各参数的更多信息，请访问 https://giscus.app
#giscus:
#  hostname: giscus.app # 如果自行托管，请替换为您的 giscus 实例主机名
#  repository: # GitHub 用户名/仓库名，例如 "daattali/beautiful-jekyll"
#  repository-id: # 您的仓库 ID，从 https://giscus.app 获取
#  category: Announcements # GitHub Discussion 帖子的分类名称
#  category-id: # 您的分类 ID，从 https://giscus.app 获取
#  mapping: pathname
#  reactions-enabled: 1
#  emit-metadata: 0
#  theme: light

################
# --- 其他 --- #
################

# 文章日期的 Ruby 日期格式
date_format: "%B %-d, %Y"

# Facebook App ID
#fb_app_id: ""

#################################################################################
# --- 以下内容通常无需修改（但您也可以按需调整） --- #
#################################################################################

# 输出选项（更多信息请查阅 Jekyll 官方文档）
timezone: "America/Toronto"
markdown: kramdown
highlighter: rouge
permalink: /:year-:month-:day-:title/
paginate: 5

kramdown:
  input: GFM

# 默认 YAML 值（更多信息请查阅 Jekyll 官方文档）
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true  # 所有博客文章启用评论
      social-share: true # 所有博客文章启用社交分享按钮
  -
    scope:
      path: "" # 非文章的文件默认使用 "page" 布局
    values:
      layout: "page"

# 生成生产站点时排除的文件
exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - screenshot.png
  - docs/

plugins:
  - jekyll-paginate
  - jekyll-sitemap

# Beautiful Jekyll / Dean Attali
# 2fc73a3a967e97599c9763d05e564189
